config:
  - .github/*
  - .github/**

docker:
  - .dockerignore
  - Dockerfile

test:
  - src/**/*.spec.js
  - src/**/*.spec.ts
  - src/**/*.spec.tsx
  - src/tests/*
  - src/tests/**
  - jest.config.js

package:
  - package.json
  - yarn.lock

LICENSE:
  - LICENSE
