name: Docker Image CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - uses: actions/checkout@v1

      - name: Build image
        run: docker build . --tag howtocards/image-uploader:dev

      - name: Push image
        run: docker push howtocards/image-uploader:dev

  latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v1

      - name: Build image
        run: docker build . --tag howtocards/image-uploader:latest

      - name: Push image
        run: docker push howtocards/image-uploader:latest

  check:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/pull/')
    steps:
      - name: Build image
        run: docker build .
